[project]
name = "rush-py"
version = "0.2.0"
description = "Simple Python interfaces for Rush modules"
readme = "README.md"
requires-python = ">=3.12"
authors = [
  { name = "Sean Laguna", email = "seanlaguna@qdx.co" },
]
dependencies = [
  "cyclopts~=4.2",
  "gql~=4.0",
  "h5py~=3.14",
  "pytest~=9.0.2",
  "rdkit~=2025.9.2",
  "requests~=2.32",
  "requests_toolbelt~=1.0",
  "zstandard~=0.23",
]


[dependency-groups]
dev = [
  "basedpyright",
  "ruff",
]

[project.scripts]
rush-exess-energy = "rush.exess:run_energy"
rush-exess-interaction-energy = "rush.exess:run_interaction_energy"
rush-exess-chelpg = "rush.exess:run_chelpg"
rush-exess-qmmm = "rush.exess:run_qmmm"
rush-exess-optimization = "rush.exess:run_optimization"

[tool.pyright]
exclude = [
  "**/node_modules",
  "**/__pycache__",
  "**/*venv*",
  "result",
  "setup.py",
]
ignore = [
  "**/node_modules",
  "**/__pycache__",
  "**/*venv*",
  "result",
  "setup.py",
]
reportIncompatibleMethodOverride = "none"
reportIncompatibleVariableOverride = "none"
reportMissingTypeStubs = "none"
reportUnknownMemberType = "none"
reportUnknownVariableType = "none"
useLibraryCodeForTypes = true
typeCheckingMode = "standard"
reportAttributeAccessIssue = "none"

[tool.uv.build-backend]
module-name = "rush"

[build-system]
requires = ["uv_build~=0.8"]
build-backend = "uv_build"
