# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/tengu-py",
        "doc_host": "https://talo.github.io",
        "git_url": "https://github.com/talo/tengu-py",
        "lib_path": "tengu_demo",
    },
    "syms": {"tengu_demo.core": {"tengu_demo.core.foo": ("core.html#foo", "tengu_demo/core.py")}},
}
