# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ArgumentPartial


class Argument(BaseModel):
    argument: "ArgumentArgument"


class ArgumentArgument(ArgumentPartial):
    pass


Argument.model_rebuild()
