# Generated by ariadne-codegen
# Source: gql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import BindingPoseConformerInteractionFields, PageInfoFull


class BindingPoseConformerInteractions(BaseModel):
    me: "BindingPoseConformerInteractionsMe"


class BindingPoseConformerInteractionsMe(BaseModel):
    account: "BindingPoseConformerInteractionsMeAccount"


class BindingPoseConformerInteractionsMeAccount(BaseModel):
    project: "BindingPoseConformerInteractionsMeAccountProject"


class BindingPoseConformerInteractionsMeAccountProject(BaseModel):
    binding_pose_conformer_interactions: "BindingPoseConformerInteractionsMeAccountProjectBindingPoseConformerInteractions"


class BindingPoseConformerInteractionsMeAccountProjectBindingPoseConformerInteractions(
    BaseModel
):
    page_info: "BindingPoseConformerInteractionsMeAccountProjectBindingPoseConformerInteractionsPageInfo" = Field(
        alias="pageInfo"
    )
    edges: List[
        "BindingPoseConformerInteractionsMeAccountProjectBindingPoseConformerInteractionsEdges"
    ]
    total_count: int


class BindingPoseConformerInteractionsMeAccountProjectBindingPoseConformerInteractionsPageInfo(
    PageInfoFull
):
    pass


class BindingPoseConformerInteractionsMeAccountProjectBindingPoseConformerInteractionsEdges(
    BaseModel
):
    cursor: str
    node: "BindingPoseConformerInteractionsMeAccountProjectBindingPoseConformerInteractionsEdgesNode"


class BindingPoseConformerInteractionsMeAccountProjectBindingPoseConformerInteractionsEdgesNode(
    BindingPoseConformerInteractionFields
):
    pass


BindingPoseConformerInteractions.model_rebuild()
BindingPoseConformerInteractionsMe.model_rebuild()
BindingPoseConformerInteractionsMeAccount.model_rebuild()
BindingPoseConformerInteractionsMeAccountProject.model_rebuild()
BindingPoseConformerInteractionsMeAccountProjectBindingPoseConformerInteractions.model_rebuild()
BindingPoseConformerInteractionsMeAccountProjectBindingPoseConformerInteractionsEdges.model_rebuild()
