# Generated by ariadne-codegen
# Source: gql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import BindingSiteConformerFields, PageInfoFull


class BindingSiteConformers(BaseModel):
    me: "BindingSiteConformersMe"


class BindingSiteConformersMe(BaseModel):
    account: "BindingSiteConformersMeAccount"


class BindingSiteConformersMeAccount(BaseModel):
    project: "BindingSiteConformersMeAccountProject"


class BindingSiteConformersMeAccountProject(BaseModel):
    binding_site_conformers: "BindingSiteConformersMeAccountProjectBindingSiteConformers"


class BindingSiteConformersMeAccountProjectBindingSiteConformers(BaseModel):
    page_info: "BindingSiteConformersMeAccountProjectBindingSiteConformersPageInfo" = (
        Field(alias="pageInfo")
    )
    edges: List["BindingSiteConformersMeAccountProjectBindingSiteConformersEdges"]
    total_count: int


class BindingSiteConformersMeAccountProjectBindingSiteConformersPageInfo(PageInfoFull):
    pass


class BindingSiteConformersMeAccountProjectBindingSiteConformersEdges(BaseModel):
    cursor: str
    node: "BindingSiteConformersMeAccountProjectBindingSiteConformersEdgesNode"


class BindingSiteConformersMeAccountProjectBindingSiteConformersEdgesNode(
    BindingSiteConformerFields
):
    pass


BindingSiteConformers.model_rebuild()
BindingSiteConformersMe.model_rebuild()
BindingSiteConformersMeAccount.model_rebuild()
BindingSiteConformersMeAccountProject.model_rebuild()
BindingSiteConformersMeAccountProjectBindingSiteConformers.model_rebuild()
BindingSiteConformersMeAccountProjectBindingSiteConformersEdges.model_rebuild()
