# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import BindingSiteConformerFields


class BindingSiteConformer(BaseModel):
    me: "BindingSiteConformerMe"


class BindingSiteConformerMe(BaseModel):
    account: "BindingSiteConformerMeAccount"


class BindingSiteConformerMeAccount(BaseModel):
    project: "BindingSiteConformerMeAccountProject"


class BindingSiteConformerMeAccountProject(BaseModel):
    binding_site_conformer: "BindingSiteConformerMeAccountProjectBindingSiteConformer"


class BindingSiteConformerMeAccountProjectBindingSiteConformer(
    BindingSiteConformerFields
):
    pass


BindingSiteConformer.model_rebuild()
BindingSiteConformerMe.model_rebuild()
BindingSiteConformerMeAccount.model_rebuild()
BindingSiteConformerMeAccountProject.model_rebuild()
