# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import BindingSiteInteractionFields


class BindingSiteInteraction(BaseModel):
    me: "BindingSiteInteractionMe"


class BindingSiteInteractionMe(BaseModel):
    account: "BindingSiteInteractionMeAccount"


class BindingSiteInteractionMeAccount(BaseModel):
    project: "BindingSiteInteractionMeAccountProject"


class BindingSiteInteractionMeAccountProject(BaseModel):
    binding_site_interaction: "BindingSiteInteractionMeAccountProjectBindingSiteInteraction"


class BindingSiteInteractionMeAccountProjectBindingSiteInteraction(
    BindingSiteInteractionFields
):
    pass


BindingSiteInteraction.model_rebuild()
BindingSiteInteractionMe.model_rebuild()
BindingSiteInteractionMeAccount.model_rebuild()
BindingSiteInteractionMeAccountProject.model_rebuild()
