# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import BindingPoseConformerInteractionFields


class CreateBindingPoseConformerInteractions(BaseModel):
    create_binding_pose_conformer_interactions: "CreateBindingPoseConformerInteractionsCreateBindingPoseConformerInteractions"


class CreateBindingPoseConformerInteractionsCreateBindingPoseConformerInteractions(
    BindingPoseConformerInteractionFields
):
    pass


CreateBindingPoseConformerInteractions.model_rebuild()
