# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ArgumentPartial


class CreateArgument(BaseModel):
    create_argument: "CreateArgumentCreateArgument"


class CreateArgumentCreateArgument(ArgumentPartial):
    pass


CreateArgument.model_rebuild()
