# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import SmolFields


class CreateSmol(BaseModel):
    create_smol: "CreateSmolCreateSmol"


class CreateSmolCreateSmol(SmolFields):
    pass


CreateSmol.model_rebuild()
