# Generated by ariadne-codegen
# Source: combined.graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class CreateProteinConformer(BaseModel):
    create_protein_conformer: "CreateProteinConformerCreateProteinConformer"


class CreateProteinConformerCreateProteinConformer(BaseModel):
    id: Any
    residues: List[int]
    name: Optional[str]
    description: Optional[str]
    tags: Optional[List[str]]


CreateProteinConformer.model_rebuild()
