# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import BindingSiteConformerFields


class CreateBindingSiteConformer(BaseModel):
    create_binding_site_conformer: "CreateBindingSiteConformerCreateBindingSiteConformer"


class CreateBindingSiteConformerCreateBindingSiteConformer(BindingSiteConformerFields):
    pass


CreateBindingSiteConformer.model_rebuild()
