# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import BindingPoseConformerFields


class CreateBindingPoseConformer(BaseModel):
    create_binding_pose_conformer: "CreateBindingPoseConformerCreateBindingPoseConformer"


class CreateBindingPoseConformerCreateBindingPoseConformer(BindingPoseConformerFields):
    pass


CreateBindingPoseConformer.model_rebuild()
