# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ProteinConformerFields


class CreateProteinConformer(BaseModel):
    create_protein_conformer: "CreateProteinConformerCreateProteinConformer"


class CreateProteinConformerCreateProteinConformer(ProteinConformerFields):
    pass


CreateProteinConformer.model_rebuild()
