# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ProteinFields


class CreateProtein(BaseModel):
    create_protein: "CreateProteinCreateProtein"


class CreateProteinCreateProtein(ProteinFields):
    pass


CreateProtein.model_rebuild()
