# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import MSAFields


class CreateMultipleSequenceAlignment(BaseModel):
    create_msa: "CreateMultipleSequenceAlignmentCreateMsa"


class CreateMultipleSequenceAlignmentCreateMsa(MSAFields):
    pass


CreateMultipleSequenceAlignment.model_rebuild()
