# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import SmolLibraryFields


class CreateSmolLibrary(BaseModel):
    create_smol_library: "CreateSmolLibraryCreateSmolLibrary"


class CreateSmolLibraryCreateSmolLibrary(SmolLibraryFields):
    pass


CreateSmolLibrary.model_rebuild()
