# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import TokenFields


class CreateToken(BaseModel):
    create_token: "CreateTokenCreateToken"


class CreateTokenCreateToken(TokenFields):
    pass


CreateToken.model_rebuild()
