# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import StructureFields


class CreateStructure(BaseModel):
    create_structure: "CreateStructureCreateStructure"


class CreateStructureCreateStructure(StructureFields):
    pass


CreateStructure.model_rebuild()
