# Generated by ariadne-codegen
# Source: combined.graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class CreateSmolConformer(BaseModel):
    create_smol_conformer: "CreateSmolConformerCreateSmolConformer"


class CreateSmolConformerCreateSmolConformer(BaseModel):
    id: Any
    residues: List[int]
    name: Optional[str]
    description: Optional[str]
    tags: Optional[List[str]]


CreateSmolConformer.model_rebuild()
