# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import SmolLibraryPartitionFields


class CreateSmolLibraryPartition(BaseModel):
    create_smol_library_partition: "CreateSmolLibraryPartitionCreateSmolLibraryPartition"


class CreateSmolLibraryPartitionCreateSmolLibraryPartition(SmolLibraryPartitionFields):
    pass


CreateSmolLibraryPartition.model_rebuild()
