# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import TagFields


class CreateTag(BaseModel):
    create_tag: "CreateTagCreateTag"


class CreateTagCreateTag(TagFields):
    pass


CreateTag.model_rebuild()
