# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import BindingSiteInteractionFields


class CreateBindingSiteInteractions(BaseModel):
    create_binding_site_interactions: "CreateBindingSiteInteractionsCreateBindingSiteInteractions"


class CreateBindingSiteInteractionsCreateBindingSiteInteractions(
    BindingSiteInteractionFields
):
    pass


CreateBindingSiteInteractions.model_rebuild()
