# Generated by ariadne-codegen
# Source: combined.graphql

from typing import Any, Optional

from .base_model import BaseModel


class CreateProject(BaseModel):
    create_project: "CreateProjectCreateProject"


class CreateProjectCreateProject(BaseModel):
    id: Any
    name: Optional[str]
    description: Optional[str]


CreateProject.model_rebuild()
