# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ProjectFields


class CreateProject(BaseModel):
    create_project: "CreateProjectCreateProject"


class CreateProjectCreateProject(ProjectFields):
    pass


CreateProject.model_rebuild()
