# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import BindingAffinityFields


class CreateBindingAffinity(BaseModel):
    create_binding_affinity: "CreateBindingAffinityCreateBindingAffinity"


class CreateBindingAffinityCreateBindingAffinity(BindingAffinityFields):
    pass


CreateBindingAffinity.model_rebuild()
