# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import BindingPoseAffinityFields


class CreateBindingPoseAffinity(BaseModel):
    create_binding_pose_affinity: "CreateBindingPoseAffinityCreateBindingPoseAffinity"


class CreateBindingPoseAffinityCreateBindingPoseAffinity(BindingPoseAffinityFields):
    pass


CreateBindingPoseAffinity.model_rebuild()
