# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteRun(BaseModel):
    delete_run: "DeleteRunDeleteRun"


class DeleteRunDeleteRun(BaseModel):
    id: Any


DeleteRun.model_rebuild()
