# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteMsa(BaseModel):
    delete_msa: "DeleteMsaDeleteMsa"


class DeleteMsaDeleteMsa(BaseModel):
    id: Any


DeleteMsa.model_rebuild()
