# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteSmolConformer(BaseModel):
    delete_smol_conformer: "DeleteSmolConformerDeleteSmolConformer"


class DeleteSmolConformerDeleteSmolConformer(BaseModel):
    id: Any


DeleteSmolConformer.model_rebuild()
