# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteBindingPoseConformer(BaseModel):
    delete_binding_pose_conformer: "DeleteBindingPoseConformerDeleteBindingPoseConformer"


class DeleteBindingPoseConformerDeleteBindingPoseConformer(BaseModel):
    id: Any


DeleteBindingPoseConformer.model_rebuild()
