# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteBindingSiteInteractions(BaseModel):
    delete_binding_site_interactions: "DeleteBindingSiteInteractionsDeleteBindingSiteInteractions"


class DeleteBindingSiteInteractionsDeleteBindingSiteInteractions(BaseModel):
    id: Any


DeleteBindingSiteInteractions.model_rebuild()
