# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteSmolLibrary(BaseModel):
    delete_smol_library: "DeleteSmolLibraryDeleteSmolLibrary"


class DeleteSmolLibraryDeleteSmolLibrary(BaseModel):
    id: Any


DeleteSmolLibrary.model_rebuild()
