# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteToken(BaseModel):
    delete_token: "DeleteTokenDeleteToken"


class DeleteTokenDeleteToken(BaseModel):
    id: Any


DeleteToken.model_rebuild()
