# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteTag(BaseModel):
    delete_tag: "DeleteTagDeleteTag"


class DeleteTagDeleteTag(BaseModel):
    id: Any


DeleteTag.model_rebuild()
