# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteProtein(BaseModel):
    delete_protein: "DeleteProteinDeleteProtein"


class DeleteProteinDeleteProtein(BaseModel):
    id: Any


DeleteProtein.model_rebuild()
