# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteProteinConformer(BaseModel):
    delete_protein_conformer: "DeleteProteinConformerDeleteProteinConformer"


class DeleteProteinConformerDeleteProteinConformer(BaseModel):
    id: Any


DeleteProteinConformer.model_rebuild()
