# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteSmolLibraryPartition(BaseModel):
    delete_smol_library_partition: "DeleteSmolLibraryPartitionDeleteSmolLibraryPartition"


class DeleteSmolLibraryPartitionDeleteSmolLibraryPartition(BaseModel):
    id: Any


DeleteSmolLibraryPartition.model_rebuild()
