# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteBindingPoseConformerInteractions(BaseModel):
    delete_binding_pose_conformer_interactions: "DeleteBindingPoseConformerInteractionsDeleteBindingPoseConformerInteractions"


class DeleteBindingPoseConformerInteractionsDeleteBindingPoseConformerInteractions(
    BaseModel
):
    id: Any


DeleteBindingPoseConformerInteractions.model_rebuild()
