# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteProject(BaseModel):
    delete_project: "DeleteProjectDeleteProject"


class DeleteProjectDeleteProject(BaseModel):
    id: Any


DeleteProject.model_rebuild()
