# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteBindingAffinity(BaseModel):
    delete_binding_affinity: "DeleteBindingAffinityDeleteBindingAffinity"


class DeleteBindingAffinityDeleteBindingAffinity(BaseModel):
    id: Any


DeleteBindingAffinity.model_rebuild()
