# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteSmol(BaseModel):
    delete_smol: "DeleteSmolDeleteSmol"


class DeleteSmolDeleteSmol(BaseModel):
    id: Any


DeleteSmol.model_rebuild()
