# Generated by ariadne-codegen
# Source: gql

from typing import Any

from .base_model import BaseModel


class DeleteStructure(BaseModel):
    delete_structure: "DeleteStructureDeleteStructure"


class DeleteStructureDeleteStructure(BaseModel):
    id: Any


DeleteStructure.model_rebuild()
