# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ModuleFull


class Deploy(BaseModel):
    deploy: "DeployDeploy"


class DeployDeploy(ModuleFull):
    pass


Deploy.model_rebuild()
