# Generated by ariadne-codegen
# Source: gql

from uuid import UUID

from .base_model import BaseModel


class Destroy(BaseModel):
    destroy: "DestroyDestroy"


class DestroyDestroy(BaseModel):
    id: UUID


Destroy.model_rebuild()
