# Generated by ariadne-codegen
# Source: schema.graphql

from enum import Enum


class AccountTier(str, Enum):
    FREE = "FREE"
    PRO = "PRO"
    STARTUP = "STARTUP"
    ACADEMIC = "ACADEMIC"
    ENTERPRISE = "ENTERPRISE"


class ActivityType(str, Enum):
    BINDING_AFFINITY = "BINDING_AFFINITY"
    TOXICITY = "TOXICITY"
    FUNCTIONAL = "FUNCTIONAL"


class BenchmarkEntityType(str, Enum):
    PROTEIN = "PROTEIN"
    PROTEIN_CONFORMER = "PROTEIN_CONFORMER"
    SMOL = "SMOL"
    SMOL_CONFORMER = "SMOL_CONFORMER"
    STRUCTURE = "STRUCTURE"
    BINDING_AFFINITY = "BINDING_AFFINITY"


class BindingSiteInteractionKind(str, Enum):
    UNKNOWN = "UNKNOWN"
    HYDROPHOBIC = "HYDROPHOBIC"
    HYDROGEN_BOND = "HYDROGEN_BOND"
    HALOGEN_BOND = "HALOGEN_BOND"
    WATER_BRIDGE = "WATER_BRIDGE"
    SALT_BRIDGE = "SALT_BRIDGE"
    PI_STACK = "PI_STACK"
    PI_CATION = "PI_CATION"
    METAL_COMPLEX = "METAL_COMPLEX"


class BoolFilter(str, Enum):
    t = "t"
    f = "f"


class DateTimeSort(str, Enum):
    asc = "asc"
    desc = "desc"


class F32Sort(str, Enum):
    asc = "asc"
    desc = "desc"


class F64Sort(str, Enum):
    asc = "asc"
    desc = "desc"


class I32Sort(str, Enum):
    asc = "asc"
    desc = "desc"


class I64Sort(str, Enum):
    asc = "asc"
    desc = "desc"


class MemUnits(str, Enum):
    B = "B"
    KB = "KB"
    MB = "MB"
    GB = "GB"
    TB = "TB"


class ModuleFailureReason(str, Enum):
    RESOLUTION = "RESOLUTION"
    DISPATCH = "DISPATCH"
    RUN = "RUN"
    STALLED = "STALLED"
    MISSING = "MISSING"
    CORRUPTED = "CORRUPTED"
    CREDITS = "CREDITS"


class ModuleInstanceStatus(str, Enum):
    CREATED = "CREATED"
    RESOLVING = "RESOLVING"
    ADMITTED = "ADMITTED"
    DISPATCHED = "DISPATCHED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    AWAITING_UPLOAD = "AWAITING_UPLOAD"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ModuleInstanceTarget(str, Enum):
    TINY = "TINY"
    GADI = "GADI"
    BULLET = "BULLET"
    BULLET_2 = "BULLET_2"
    BULLET_3 = "BULLET_3"
    BULLET_4 = "BULLET_4"
    SETONIX = "SETONIX"
    GADI_GPU = "GADI_GPU"
    BULLET_GPU = "BULLET_GPU"
    BULLET_2_GPU = "BULLET_2_GPU"
    BULLET_3_GPU = "BULLET_3_GPU"
    BULLET_4_GPU = "BULLET_4_GPU"
    SETONIX_GPU = "SETONIX_GPU"
    GADI_EXPRESS = "GADI_EXPRESS"
    SETONIX_EXPRESS = "SETONIX_EXPRESS"


class ObjectFormat(str, Enum):
    json = "json"
    bin = "bin"


class OrderBy(str, Enum):
    ASC = "ASC"
    DESC = "DESC"


class PiStackKind(str, Enum):
    UNKNOWN = "UNKNOWN"
    P = "P"
    T = "T"


class RunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    DONE = "DONE"
    ERROR = "ERROR"
    CANCELLED = "CANCELLED"


class StringSort(str, Enum):
    asc = "asc"
    desc = "desc"


class TaggedType(str, Enum):
    structure = "structure"
    protein = "protein"
    protein_conformer = "protein_conformer"
    smol = "smol"
    smol_conformer = "smol_conformer"
    run = "run"
    module = "module"
    module_instance = "module_instance"


class U64Sort(str, Enum):
    asc = "asc"
    desc = "desc"


class UuidSort(str, Enum):
    asc = "asc"
    desc = "desc"
