# Generated by ariadne-codegen
# Source: schema.graphql

from enum import Enum


class AccountTier(str, Enum):
    FREE = "FREE"
    PRO = "PRO"
    STARTUP = "STARTUP"
    ACADEMIC = "ACADEMIC"
    ENTERPRISE = "ENTERPRISE"


class DateTimeSort(str, Enum):
    asc = "asc"
    desc = "desc"


class MemUnits(str, Enum):
    B = "B"
    KB = "KB"
    MB = "MB"
    GB = "GB"
    TB = "TB"


class ModuleFailureReason(str, Enum):
    RESOLUTION = "RESOLUTION"
    DISPATCH = "DISPATCH"
    RUN = "RUN"
    STALLED = "STALLED"
    MISSING = "MISSING"
    CORRUPTED = "CORRUPTED"


class ModuleInstanceStatus(str, Enum):
    CREATED = "CREATED"
    RESOLVING = "RESOLVING"
    ADMITTED = "ADMITTED"
    DISPATCHED = "DISPATCHED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    AWAITING_UPLOAD = "AWAITING_UPLOAD"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ModuleInstanceTarget(str, Enum):
    TINY = "TINY"
    GADI = "GADI"
    BULLET = "BULLET"
    BULLET_2 = "BULLET_2"
    BULLET_3 = "BULLET_3"
    BULLET_4 = "BULLET_4"
    SETONIX = "SETONIX"
    GADI_GPU = "GADI_GPU"
    BULLET_GPU = "BULLET_GPU"
    BULLET_2_GPU = "BULLET_2_GPU"
    BULLET_3_GPU = "BULLET_3_GPU"
    BULLET_4_GPU = "BULLET_4_GPU"
    SETONIX_GPU = "SETONIX_GPU"
    GADI_EXPRESS = "GADI_EXPRESS"
    SETONIX_EXPRESS = "SETONIX_EXPRESS"


class ObjectFormat(str, Enum):
    json = "json"
    bin = "bin"


class OrderBy(str, Enum):
    ASC = "ASC"
    DESC = "DESC"


class ProtocolStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    DONE = "DONE"
    ERROR = "ERROR"


class StringSort(str, Enum):
    asc = "asc"
    desc = "desc"


class U64Sort(str, Enum):
    asc = "asc"
    desc = "desc"


class UuidSort(str, Enum):
    asc = "asc"
    desc = "desc"
