# Generated by ariadne-codegen
# Source: gql

from typing import Optional

from .base_model import BaseModel
from .fragments import UserFields


class Login(BaseModel):
    login: Optional["LoginLogin"]


class LoginLogin(UserFields):
    pass


Login.model_rebuild()
