# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import UserFields


class Me(BaseModel):
    me: "MeMe"


class MeMe(UserFields):
    pass


Me.model_rebuild()
