# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ModuleFull


class Module(BaseModel):
    module: "ModuleModule"


class ModuleModule(ModuleFull):
    pass


Module.model_rebuild()
