# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ModuleInstanceBase


class ModuleInstanceMinimal(BaseModel):
    module_instance: "ModuleInstanceMinimalModuleInstance"


class ModuleInstanceMinimalModuleInstance(ModuleInstanceBase):
    pass


ModuleInstanceMinimal.model_rebuild()
