# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import MSAFields


class Msa(BaseModel):
    me: "MsaMe"


class MsaMe(BaseModel):
    account: "MsaMeAccount"


class MsaMeAccount(BaseModel):
    project: "MsaMeAccountProject"


class MsaMeAccountProject(BaseModel):
    msa: "MsaMeAccountProjectMsa"


class MsaMeAccountProjectMsa(MSAFields):
    pass


Msa.model_rebuild()
MsaMe.model_rebuild()
MsaMeAccount.model_rebuild()
MsaMeAccountProject.model_rebuild()
