# Generated by ariadne-codegen
# Source: gql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import MSAFields, PageInfoFull


class Msas(BaseModel):
    me: "MsasMe"


class MsasMe(BaseModel):
    account: "MsasMeAccount"


class MsasMeAccount(BaseModel):
    project: "MsasMeAccountProject"


class MsasMeAccountProject(BaseModel):
    msas: "MsasMeAccountProjectMsas"


class MsasMeAccountProjectMsas(BaseModel):
    page_info: "MsasMeAccountProjectMsasPageInfo" = Field(alias="pageInfo")
    edges: List["MsasMeAccountProjectMsasEdges"]
    total_count: int


class MsasMeAccountProjectMsasPageInfo(PageInfoFull):
    pass


class MsasMeAccountProjectMsasEdges(BaseModel):
    cursor: str
    node: "MsasMeAccountProjectMsasEdgesNode"


class MsasMeAccountProjectMsasEdgesNode(MSAFields):
    pass


Msas.model_rebuild()
MsasMe.model_rebuild()
MsasMeAccount.model_rebuild()
MsasMeAccountProject.model_rebuild()
MsasMeAccountProjectMsas.model_rebuild()
MsasMeAccountProjectMsasEdges.model_rebuild()
