# Generated by ariadne-codegen
# Source: combined.graphql

from typing import Optional

from .base_model import BaseModel


class ObjectUrl(BaseModel):
    object: Optional["ObjectUrlObject"]


class ObjectUrlObject(BaseModel):
    url: str
