# Generated by ariadne-codegen
# Source: gql

from typing import Any, Optional

from .base_model import BaseModel


class ObjectContents(BaseModel):
    object_path: "ObjectContentsObjectPath"


class ObjectContentsObjectPath(BaseModel):
    contents: Optional[Any]


ObjectContents.model_rebuild()
