# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ObjectFields


class Object(BaseModel):
    object: "ObjectObject"


class ObjectObject(ObjectFields):
    pass


Object.model_rebuild()
