# Generated by ariadne-codegen
# Source: combined.graphql

from typing import Any

from .base_model import BaseModel


class ObjectContents(BaseModel):
    object_path: "ObjectContentsObjectPath"


class ObjectContentsObjectPath(BaseModel):
    contents: Any


ObjectContents.model_rebuild()
