# Generated by ariadne-codegen
# Source: combined.graphql

from typing import Any, Optional

from .base_model import BaseModel


class ObjectContents(BaseModel):
    object: Optional["ObjectContentsObject"]


class ObjectContentsObject(BaseModel):
    contents: Any
