# Generated by ariadne-codegen
# Source: combined.graphql

from .base_model import BaseModel


class ObjectUrl(BaseModel):
    object_path: "ObjectUrlObjectPath"


class ObjectUrlObjectPath(BaseModel):
    url: str


ObjectUrl.model_rebuild()
