# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import BindingSiteInteractionFields


class PatchBindingSiteInteractions(BaseModel):
    patch_binding_site_interactions: "PatchBindingSiteInteractionsPatchBindingSiteInteractions"


class PatchBindingSiteInteractionsPatchBindingSiteInteractions(
    BindingSiteInteractionFields
):
    pass


PatchBindingSiteInteractions.model_rebuild()
