# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import BindingPoseConformerFields


class PatchBindingPoseConformer(BaseModel):
    patch_binding_pose_conformer: "PatchBindingPoseConformerPatchBindingPoseConformer"


class PatchBindingPoseConformerPatchBindingPoseConformer(BindingPoseConformerFields):
    pass


PatchBindingPoseConformer.model_rebuild()
