# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import StructureFields


class PatchStructure(BaseModel):
    patch_structure: "PatchStructurePatchStructure"


class PatchStructurePatchStructure(StructureFields):
    pass


PatchStructure.model_rebuild()
