# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ProteinConformerFields


class PatchProteinConformer(BaseModel):
    patch_protein_conformer: "PatchProteinConformerPatchProteinConformer"


class PatchProteinConformerPatchProteinConformer(ProteinConformerFields):
    pass


PatchProteinConformer.model_rebuild()
