# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ProteinFields


class PatchProtein(BaseModel):
    patch_protein: "PatchProteinPatchProtein"


class PatchProteinPatchProtein(ProteinFields):
    pass


PatchProtein.model_rebuild()
