# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import SmolLibraryFields


class PatchSmolLibrary(BaseModel):
    patch_smol_library: "PatchSmolLibraryPatchSmolLibrary"


class PatchSmolLibraryPatchSmolLibrary(SmolLibraryFields):
    pass


PatchSmolLibrary.model_rebuild()
