# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ProjectFields


class PatchProject(BaseModel):
    patch_project: "PatchProjectPatchProject"


class PatchProjectPatchProject(ProjectFields):
    pass


PatchProject.model_rebuild()
