# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import SmolFields


class PatchSmol(BaseModel):
    patch_smol: "PatchSmolPatchSmol"


class PatchSmolPatchSmol(SmolFields):
    pass


PatchSmol.model_rebuild()
