# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import MSAFields


class PatchMsa(BaseModel):
    patch_msa: "PatchMsaPatchMsa"


class PatchMsaPatchMsa(MSAFields):
    pass


PatchMsa.model_rebuild()
