# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import SmolConformerFields


class PatchSmolConformer(BaseModel):
    patch_smol_conformer: "PatchSmolConformerPatchSmolConformer"


class PatchSmolConformerPatchSmolConformer(SmolConformerFields):
    pass


PatchSmolConformer.model_rebuild()
