# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import TagFields


class PatchTag(BaseModel):
    patch_tag: "PatchTagPatchTag"


class PatchTagPatchTag(TagFields):
    pass


PatchTag.model_rebuild()
