# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import BindingPoseConformerInteractionFields


class PatchBindingPoseConformerInteractions(BaseModel):
    patch_binding_pose_conformer_interactions: "PatchBindingPoseConformerInteractionsPatchBindingPoseConformerInteractions"


class PatchBindingPoseConformerInteractionsPatchBindingPoseConformerInteractions(
    BindingPoseConformerInteractionFields
):
    pass


PatchBindingPoseConformerInteractions.model_rebuild()
