# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import BindingAffinityFields


class PatchBindingAffinity(BaseModel):
    patch_binding_affinity: "PatchBindingAffinityPatchBindingAffinity"


class PatchBindingAffinityPatchBindingAffinity(BindingAffinityFields):
    pass


PatchBindingAffinity.model_rebuild()
