# Generated by ariadne-codegen
# Source: combined.graphql

from datetime import datetime
from typing import Any, List, Optional

from .base_model import BaseModel


class Project(BaseModel):
    me: "ProjectMe"


class ProjectMe(BaseModel):
    account: "ProjectMeAccount"


class ProjectMeAccount(BaseModel):
    project: "ProjectMeAccountProject"


class ProjectMeAccountProject(BaseModel):
    id: Any
    created_at: datetime
    updated_at: datetime
    deleted_at: Optional[datetime]
    name: Optional[str]
    description: Optional[str]
    run_id: Optional[Any]
    tags: Optional[List[str]]


Project.model_rebuild()
ProjectMe.model_rebuild()
ProjectMeAccount.model_rebuild()
