# Generated by ariadne-codegen
# Source: gql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import PageInfoFull, ProjectFields


class Projects(BaseModel):
    me: "ProjectsMe"


class ProjectsMe(BaseModel):
    account: "ProjectsMeAccount"


class ProjectsMeAccount(BaseModel):
    projects: "ProjectsMeAccountProjects"


class ProjectsMeAccountProjects(BaseModel):
    page_info: "ProjectsMeAccountProjectsPageInfo" = Field(alias="pageInfo")
    edges: List["ProjectsMeAccountProjectsEdges"]
    total_count: int


class ProjectsMeAccountProjectsPageInfo(PageInfoFull):
    pass


class ProjectsMeAccountProjectsEdges(BaseModel):
    cursor: str
    node: "ProjectsMeAccountProjectsEdgesNode"


class ProjectsMeAccountProjectsEdgesNode(ProjectFields):
    pass


Projects.model_rebuild()
ProjectsMe.model_rebuild()
ProjectsMeAccount.model_rebuild()
ProjectsMeAccountProjects.model_rebuild()
ProjectsMeAccountProjectsEdges.model_rebuild()
