# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ProjectFields


class Project(BaseModel):
    me: "ProjectMe"


class ProjectMe(BaseModel):
    account: "ProjectMeAccount"


class ProjectMeAccount(BaseModel):
    project: "ProjectMeAccountProject"


class ProjectMeAccountProject(ProjectFields):
    pass


Project.model_rebuild()
ProjectMe.model_rebuild()
ProjectMeAccount.model_rebuild()
