# Generated by ariadne-codegen
# Source: gql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import PageInfoFull, ProteinFields


class Proteins(BaseModel):
    me: "ProteinsMe"


class ProteinsMe(BaseModel):
    account: "ProteinsMeAccount"


class ProteinsMeAccount(BaseModel):
    project: "ProteinsMeAccountProject"


class ProteinsMeAccountProject(BaseModel):
    proteins: "ProteinsMeAccountProjectProteins"


class ProteinsMeAccountProjectProteins(BaseModel):
    page_info: "ProteinsMeAccountProjectProteinsPageInfo" = Field(alias="pageInfo")
    edges: List["ProteinsMeAccountProjectProteinsEdges"]
    total_count: int


class ProteinsMeAccountProjectProteinsPageInfo(PageInfoFull):
    pass


class ProteinsMeAccountProjectProteinsEdges(BaseModel):
    cursor: str
    node: "ProteinsMeAccountProjectProteinsEdgesNode"


class ProteinsMeAccountProjectProteinsEdgesNode(ProteinFields):
    pass


Proteins.model_rebuild()
ProteinsMe.model_rebuild()
ProteinsMeAccount.model_rebuild()
ProteinsMeAccountProject.model_rebuild()
ProteinsMeAccountProjectProteins.model_rebuild()
ProteinsMeAccountProjectProteinsEdges.model_rebuild()
