# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ProteinConformerFields


class ProteinConformer(BaseModel):
    me: "ProteinConformerMe"


class ProteinConformerMe(BaseModel):
    account: "ProteinConformerMeAccount"


class ProteinConformerMeAccount(BaseModel):
    project: "ProteinConformerMeAccountProject"


class ProteinConformerMeAccountProject(BaseModel):
    protein_conformer: "ProteinConformerMeAccountProjectProteinConformer"


class ProteinConformerMeAccountProjectProteinConformer(ProteinConformerFields):
    pass


ProteinConformer.model_rebuild()
ProteinConformerMe.model_rebuild()
ProteinConformerMeAccount.model_rebuild()
ProteinConformerMeAccountProject.model_rebuild()
