# Generated by ariadne-codegen
# Source: combined.graphql

from datetime import datetime
from typing import Any, List, Optional

from .base_model import BaseModel


class Protein(BaseModel):
    me: "ProteinMe"


class ProteinMe(BaseModel):
    account: "ProteinMeAccount"


class ProteinMeAccount(BaseModel):
    project: "ProteinMeAccountProject"


class ProteinMeAccountProject(BaseModel):
    protein: "ProteinMeAccountProjectProtein"


class ProteinMeAccountProjectProtein(BaseModel):
    id: Any
    sequence: str
    created_at: datetime
    updated_at: datetime
    deleted_at: Optional[datetime]
    name: Optional[str]
    description: Optional[str]
    run_id: Optional[Any]
    tags: Optional[List[str]]


Protein.model_rebuild()
ProteinMe.model_rebuild()
ProteinMeAccount.model_rebuild()
ProteinMeAccountProject.model_rebuild()
