# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ProteinFields


class Protein(BaseModel):
    me: "ProteinMe"


class ProteinMe(BaseModel):
    account: "ProteinMeAccount"


class ProteinMeAccount(BaseModel):
    project: "ProteinMeAccountProject"


class ProteinMeAccountProject(BaseModel):
    protein: "ProteinMeAccountProjectProtein"


class ProteinMeAccountProjectProtein(ProteinFields):
    pass


Protein.model_rebuild()
ProteinMe.model_rebuild()
ProteinMeAccount.model_rebuild()
ProteinMeAccountProject.model_rebuild()
