# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import RunFields


class Run(BaseModel):
    me: "RunMe"


class RunMe(BaseModel):
    account: "RunMeAccount"


class RunMeAccount(BaseModel):
    project: "RunMeAccountProject"


class RunMeAccountProject(BaseModel):
    run: "RunMeAccountProjectRun"


class RunMeAccountProjectRun(RunFields):
    pass


Run.model_rebuild()
RunMe.model_rebuild()
RunMeAccount.model_rebuild()
RunMeAccountProject.model_rebuild()
