# Generated by ariadne-codegen
# Source: combined.graphql

from datetime import datetime
from typing import Any, List, Optional

from .base_model import BaseModel
from .enums import RunStatus


class Run(BaseModel):
    me: "RunMe"


class RunMe(BaseModel):
    account: "RunMeAccount"


class RunMeAccount(BaseModel):
    project: "RunMeAccountProject"


class RunMeAccountProject(BaseModel):
    run: "RunMeAccountProjectRun"


class RunMeAccountProjectRun(BaseModel):
    id: Any
    rex: str
    result: Optional[Any]
    trace: Optional[Any]
    module_lock: Any
    status: RunStatus
    created_at: datetime
    updated_at: datetime
    deleted_at: Optional[datetime]
    name: Optional[str]
    description: Optional[str]
    run_id: Optional[Any]
    tags: Optional[List[str]]


Run.model_rebuild()
RunMe.model_rebuild()
RunMeAccount.model_rebuild()
RunMeAccountProject.model_rebuild()
