# Generated by ariadne-codegen
# Source: gql

from typing import List
from uuid import UUID

from .base_model import BaseModel


class RunModuleInstance(BaseModel):
    run_module_instance: "RunModuleInstanceRunModuleInstance"


class RunModuleInstanceRunModuleInstance(BaseModel):
    id: UUID
    outs: List["RunModuleInstanceRunModuleInstanceOuts"]


class RunModuleInstanceRunModuleInstanceOuts(BaseModel):
    id: UUID


RunModuleInstance.model_rebuild()
RunModuleInstanceRunModuleInstance.model_rebuild()
