# Generated by ariadne-codegen
# Source: gql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import PageInfoFull, RunFields


class Runs(BaseModel):
    me: "RunsMe"


class RunsMe(BaseModel):
    account: "RunsMeAccount"


class RunsMeAccount(BaseModel):
    project: "RunsMeAccountProject"


class RunsMeAccountProject(BaseModel):
    runs: "RunsMeAccountProjectRuns"


class RunsMeAccountProjectRuns(BaseModel):
    page_info: "RunsMeAccountProjectRunsPageInfo" = Field(alias="pageInfo")
    edges: List["RunsMeAccountProjectRunsEdges"]
    total_count: int


class RunsMeAccountProjectRunsPageInfo(PageInfoFull):
    pass


class RunsMeAccountProjectRunsEdges(BaseModel):
    cursor: str
    node: "RunsMeAccountProjectRunsEdgesNode"


class RunsMeAccountProjectRunsEdgesNode(RunFields):
    pass


Runs.model_rebuild()
RunsMe.model_rebuild()
RunsMeAccount.model_rebuild()
RunsMeAccountProject.model_rebuild()
RunsMeAccountProjectRuns.model_rebuild()
RunsMeAccountProjectRunsEdges.model_rebuild()
