# Generated by ariadne-codegen
# Source: gql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import PageInfoFull, SmolLibraryFields


class SmolLibraries(BaseModel):
    smol_libraries: "SmolLibrariesSmolLibraries"


class SmolLibrariesSmolLibraries(BaseModel):
    page_info: "SmolLibrariesSmolLibrariesPageInfo" = Field(alias="pageInfo")
    edges: List["SmolLibrariesSmolLibrariesEdges"]
    total_count: int


class SmolLibrariesSmolLibrariesPageInfo(PageInfoFull):
    pass


class SmolLibrariesSmolLibrariesEdges(BaseModel):
    cursor: str
    node: "SmolLibrariesSmolLibrariesEdgesNode"


class SmolLibrariesSmolLibrariesEdgesNode(SmolLibraryFields):
    pass


SmolLibraries.model_rebuild()
SmolLibrariesSmolLibraries.model_rebuild()
SmolLibrariesSmolLibrariesEdges.model_rebuild()
