# Generated by ariadne-codegen
# Source: combined.graphql

from datetime import datetime
from typing import Any, List, Optional

from .base_model import BaseModel


class Smol(BaseModel):
    me: "SmolMe"


class SmolMe(BaseModel):
    account: "SmolMeAccount"


class SmolMeAccount(BaseModel):
    project: "SmolMeAccountProject"


class SmolMeAccountProject(BaseModel):
    smol: "SmolMeAccountProjectSmol"


class SmolMeAccountProjectSmol(BaseModel):
    id: Any
    smi: Optional[str]
    inchi: Optional[str]
    data_blocks: Optional[List[List[str]]]
    created_at: datetime
    updated_at: datetime
    deleted_at: Optional[datetime]
    name: Optional[str]
    description: Optional[str]
    run_id: Optional[Any]
    tags: Optional[List[str]]


Smol.model_rebuild()
SmolMe.model_rebuild()
SmolMeAccount.model_rebuild()
SmolMeAccountProject.model_rebuild()
