# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import SmolLibraryFields


class SmolLibrary(BaseModel):
    smol_library: "SmolLibrarySmolLibrary"


class SmolLibrarySmolLibrary(SmolLibraryFields):
    pass


SmolLibrary.model_rebuild()
