# Generated by ariadne-codegen
# Source: gql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import PageInfoFull, SmolFields


class Smols(BaseModel):
    me: "SmolsMe"


class SmolsMe(BaseModel):
    account: "SmolsMeAccount"


class SmolsMeAccount(BaseModel):
    project: "SmolsMeAccountProject"


class SmolsMeAccountProject(BaseModel):
    smols: "SmolsMeAccountProjectSmols"


class SmolsMeAccountProjectSmols(BaseModel):
    page_info: "SmolsMeAccountProjectSmolsPageInfo" = Field(alias="pageInfo")
    edges: List["SmolsMeAccountProjectSmolsEdges"]
    total_count: int


class SmolsMeAccountProjectSmolsPageInfo(PageInfoFull):
    pass


class SmolsMeAccountProjectSmolsEdges(BaseModel):
    cursor: str
    node: "SmolsMeAccountProjectSmolsEdgesNode"


class SmolsMeAccountProjectSmolsEdgesNode(SmolFields):
    pass


Smols.model_rebuild()
SmolsMe.model_rebuild()
SmolsMeAccount.model_rebuild()
SmolsMeAccountProject.model_rebuild()
SmolsMeAccountProjectSmols.model_rebuild()
SmolsMeAccountProjectSmolsEdges.model_rebuild()
