# Generated by ariadne-codegen
# Source: gql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import PageInfoFull, SmolLibraryPartitionFields


class SmolLibraryPartitions(BaseModel):
    smol_library: "SmolLibraryPartitionsSmolLibrary"


class SmolLibraryPartitionsSmolLibrary(BaseModel):
    partitions: "SmolLibraryPartitionsSmolLibraryPartitions"


class SmolLibraryPartitionsSmolLibraryPartitions(BaseModel):
    page_info: "SmolLibraryPartitionsSmolLibraryPartitionsPageInfo" = Field(
        alias="pageInfo"
    )
    edges: List["SmolLibraryPartitionsSmolLibraryPartitionsEdges"]
    total_count: int


class SmolLibraryPartitionsSmolLibraryPartitionsPageInfo(PageInfoFull):
    pass


class SmolLibraryPartitionsSmolLibraryPartitionsEdges(BaseModel):
    cursor: str
    node: "SmolLibraryPartitionsSmolLibraryPartitionsEdgesNode"


class SmolLibraryPartitionsSmolLibraryPartitionsEdgesNode(SmolLibraryPartitionFields):
    pass


SmolLibraryPartitions.model_rebuild()
SmolLibraryPartitionsSmolLibrary.model_rebuild()
SmolLibraryPartitionsSmolLibraryPartitions.model_rebuild()
SmolLibraryPartitionsSmolLibraryPartitionsEdges.model_rebuild()
