# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import SmolFields


class Smol(BaseModel):
    me: "SmolMe"


class SmolMe(BaseModel):
    account: "SmolMeAccount"


class SmolMeAccount(BaseModel):
    project: "SmolMeAccountProject"


class SmolMeAccountProject(BaseModel):
    smol: "SmolMeAccountProjectSmol"


class SmolMeAccountProjectSmol(SmolFields):
    pass


Smol.model_rebuild()
SmolMe.model_rebuild()
SmolMeAccount.model_rebuild()
SmolMeAccountProject.model_rebuild()
