# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import SmolConformerFields


class SmolConformer(BaseModel):
    me: "SmolConformerMe"


class SmolConformerMe(BaseModel):
    account: "SmolConformerMeAccount"


class SmolConformerMeAccount(BaseModel):
    project: "SmolConformerMeAccountProject"


class SmolConformerMeAccountProject(BaseModel):
    smol_conformer: "SmolConformerMeAccountProjectSmolConformer"


class SmolConformerMeAccountProjectSmolConformer(SmolConformerFields):
    pass


SmolConformer.model_rebuild()
SmolConformerMe.model_rebuild()
SmolConformerMeAccount.model_rebuild()
SmolConformerMeAccountProject.model_rebuild()
