# Generated by ariadne-codegen
# Source: gql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import PageInfoFull, SmolConformerFields


class SmolConformers(BaseModel):
    me: "SmolConformersMe"


class SmolConformersMe(BaseModel):
    account: "SmolConformersMeAccount"


class SmolConformersMeAccount(BaseModel):
    project: "SmolConformersMeAccountProject"


class SmolConformersMeAccountProject(BaseModel):
    smol_conformers: "SmolConformersMeAccountProjectSmolConformers"


class SmolConformersMeAccountProjectSmolConformers(BaseModel):
    page_info: "SmolConformersMeAccountProjectSmolConformersPageInfo" = Field(
        alias="pageInfo"
    )
    edges: List["SmolConformersMeAccountProjectSmolConformersEdges"]
    total_count: int


class SmolConformersMeAccountProjectSmolConformersPageInfo(PageInfoFull):
    pass


class SmolConformersMeAccountProjectSmolConformersEdges(BaseModel):
    cursor: str
    node: "SmolConformersMeAccountProjectSmolConformersEdgesNode"


class SmolConformersMeAccountProjectSmolConformersEdgesNode(SmolConformerFields):
    pass


SmolConformers.model_rebuild()
SmolConformersMe.model_rebuild()
SmolConformersMeAccount.model_rebuild()
SmolConformersMeAccountProject.model_rebuild()
SmolConformersMeAccountProjectSmolConformers.model_rebuild()
SmolConformersMeAccountProjectSmolConformersEdges.model_rebuild()
