# Generated by ariadne-codegen
# Source: combined.graphql

from datetime import datetime
from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class SmolTautomer(BaseModel):
    smol_tautomer: Optional["SmolTautomerSmolTautomer"]


class SmolTautomerSmolTautomer(BaseModel):
    id: Any
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    deleted_at: Optional[datetime] = Field(alias="deletedAt")
    data: Optional["SmolTautomerSmolTautomerData"]
    tags: List[str]


class SmolTautomerSmolTautomerData(BaseModel):
    name: Optional[str]
    inchi: str
