# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import StructureFields


class Structure(BaseModel):
    me: "StructureMe"


class StructureMe(BaseModel):
    account: "StructureMeAccount"


class StructureMeAccount(BaseModel):
    project: "StructureMeAccountProject"


class StructureMeAccountProject(BaseModel):
    structure: "StructureMeAccountProjectStructure"


class StructureMeAccountProjectStructure(StructureFields):
    pass


Structure.model_rebuild()
StructureMe.model_rebuild()
StructureMeAccount.model_rebuild()
StructureMeAccountProject.model_rebuild()
