# Generated by ariadne-codegen
# Source: combined.graphql

from datetime import datetime
from typing import Any, List, Optional

from .base_model import BaseModel


class Structure(BaseModel):
    me: "StructureMe"


class StructureMe(BaseModel):
    account: "StructureMeAccount"


class StructureMeAccount(BaseModel):
    project: "StructureMeAccountProject"


class StructureMeAccountProject(BaseModel):
    structure: "StructureMeAccountProjectStructure"


class StructureMeAccountProjectStructure(BaseModel):
    id: Any
    rcsb_id: Optional[str]
    topology: Any
    residues: Any
    chains: Any
    created_at: datetime
    updated_at: datetime
    deleted_at: Optional[datetime]
    name: Optional[str]
    description: Optional[str]
    run_id: Optional[Any]
    tags: Optional[List[str]]


Structure.model_rebuild()
StructureMe.model_rebuild()
StructureMeAccount.model_rebuild()
StructureMeAccountProject.model_rebuild()
