# Generated by ariadne-codegen
# Source: gql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import PageInfoFull, StructureFields


class Structures(BaseModel):
    me: "StructuresMe"


class StructuresMe(BaseModel):
    account: "StructuresMeAccount"


class StructuresMeAccount(BaseModel):
    project: "StructuresMeAccountProject"


class StructuresMeAccountProject(BaseModel):
    structures: "StructuresMeAccountProjectStructures"


class StructuresMeAccountProjectStructures(BaseModel):
    page_info: "StructuresMeAccountProjectStructuresPageInfo" = Field(alias="pageInfo")
    edges: List["StructuresMeAccountProjectStructuresEdges"]
    total_count: int


class StructuresMeAccountProjectStructuresPageInfo(PageInfoFull):
    pass


class StructuresMeAccountProjectStructuresEdges(BaseModel):
    cursor: str
    node: "StructuresMeAccountProjectStructuresEdgesNode"


class StructuresMeAccountProjectStructuresEdgesNode(StructureFields):
    pass


Structures.model_rebuild()
StructuresMe.model_rebuild()
StructuresMeAccount.model_rebuild()
StructuresMeAccountProject.model_rebuild()
StructuresMeAccountProjectStructures.model_rebuild()
StructuresMeAccountProjectStructuresEdges.model_rebuild()
