# Generated by ariadne-codegen
# Source: gql

from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class UpdateAccountConfig(BaseModel):
    update_account_config: "UpdateAccountConfigUpdateAccountConfig"


class UpdateAccountConfigUpdateAccountConfig(BaseModel):
    config_account: Optional[UUID]
    bucket_config: Optional["UpdateAccountConfigUpdateAccountConfigBucketConfig"]


class UpdateAccountConfigUpdateAccountConfigBucketConfig(BaseModel):
    data_bucket: str
    log_bucket: str
    bucket_region: str


UpdateAccountConfig.model_rebuild()
UpdateAccountConfigUpdateAccountConfig.model_rebuild()
