# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ObjectFields


class UploadObject(BaseModel):
    upload_object: "UploadObjectUploadObject"


class UploadObjectUploadObject(ObjectFields):
    pass


UploadObject.model_rebuild()
