# Generated by ariadne-codegen
# Source: combined.graphql

from uuid import UUID

from .base_model import BaseModel
from .enums import ObjectFormat


class UploadObject(BaseModel):
    upload_object: "UploadObjectUploadObject"


class UploadObjectUploadObject(BaseModel):
    id: UUID
    object: "UploadObjectUploadObjectObject"


class UploadObjectUploadObjectObject(BaseModel):
    path: str
    size: int
    format: ObjectFormat


UploadObject.model_rebuild()
UploadObjectUploadObject.model_rebuild()
