# Generated by ariadne-codegen
# Source: combined.graphql

from typing import Any, List, Optional
from uuid import UUID

from .base_model import BaseModel
from .enums import ObjectFormat


class UploadLargeObject(BaseModel):
    upload_large_object: "UploadLargeObjectUploadLargeObject"


class UploadLargeObjectUploadLargeObject(BaseModel):
    upload_url: str
    descriptor: "UploadLargeObjectUploadLargeObjectDescriptor"


class UploadLargeObjectUploadLargeObjectDescriptor(BaseModel):
    id: UUID
    name: Optional[str]
    description: Optional[str]
    type_info: Any
    object: "UploadLargeObjectUploadLargeObjectDescriptorObject"
    tags: Optional[List[str]]


class UploadLargeObjectUploadLargeObjectDescriptorObject(BaseModel):
    format: ObjectFormat
    size: int
    path: str


UploadLargeObject.model_rebuild()
UploadLargeObjectUploadLargeObject.model_rebuild()
UploadLargeObjectUploadLargeObjectDescriptor.model_rebuild()
