# Generated by ariadne-codegen
# Source: gql

from .base_model import BaseModel
from .fragments import ObjectFields


class UploadLargeObject(BaseModel):
    upload_large_object: "UploadLargeObjectUploadLargeObject"


class UploadLargeObjectUploadLargeObject(BaseModel):
    upload_url: str
    descriptor: "UploadLargeObjectUploadLargeObjectDescriptor"


class UploadLargeObjectUploadLargeObjectDescriptor(ObjectFields):
    pass


UploadLargeObject.model_rebuild()
UploadLargeObjectUploadLargeObject.model_rebuild()
