project:
  type: website

format:
  html:
    theme:
    - cosmo
    - styles.scss
    css: styles.scss
    toc: true
    highlight-style: github

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    logo: assets/img/logo.png
    right:
      - text: "API Docs"
        href: "https://talo.github.io/rush-py/api"
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]